// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBK2Gwj_FqB5jlTkO1AcXkZOVbmyS4BCw',
    appId: '1:673999952183:web:75344fc39f8d60ae99e2b2',
    messagingSenderId: '673999952183',
    projectId: 'we-chat-cc3c2',
    authDomain: 'we-chat-cc3c2.firebaseapp.com',
    storageBucket: 'we-chat-cc3c2.appspot.com',
    measurementId: 'G-BWXYNEXC9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClyASiOgQF02fon3LKChg0fKK-Eaw-bcU',
    appId: '1:673999952183:android:dcb6a0ec0ddb214299e2b2',
    messagingSenderId: '673999952183',
    projectId: 'we-chat-cc3c2',
    storageBucket: 'we-chat-cc3c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmNDGZImy-ABjYxvx6ou2uOHdBLYr7F_M',
    appId: '1:673999952183:ios:7f29ff4465cc5a0599e2b2',
    messagingSenderId: '673999952183',
    projectId: 'we-chat-cc3c2',
    storageBucket: 'we-chat-cc3c2.appspot.com',
    iosBundleId: 'com.example.weChat',
  );
}
